version: '{build}'

environment:
  pypipw:
    secure: AnvQqXXhbyfD5/CeJkbivk088RZBnIObU2mXBLH2paw=

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python37-x64\python.exe

branches:
   only:
      - master

install:
  - cmd: "%PYTHON% -m pip install --upgrade pip wheel twine"

build_script:
  - cmd: "%PYTHON% -m pip install ."

artifacts:
  - path: dist\*

after_test:
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: RLBotOfficial >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %pypipw% >> %USERPROFILE%\\.pypirc"
  - python setup.py bdist_wheel sdist

on_success:
  - cmd: "%PYTHON% -m twine upload dist\\*"
